# Generated by Django 3.2.3 on 2022-03-25 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ToDoList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('todolist', models.CharField(max_length=200)),
                ('date', models.DateTimeField(max_length=50)),
            ],
        ),
    ]
